### ISSUE TITLE
cmake refactoring next steps

### ISSUE THREAD

**Issue by a4z** [grantila/q#4]
besides today pull request following next tasks are planned 

- [x]  enable ctest if testing is enabled
`make test` should run the test

- [x]  add pkg config file generated via cmake

- [x]  add a make install target 
will make this for Linux 32/64 bit
unsure about the default locations on mac but this should be easy atopable
Windows, has no make install , hahaha

This is less an issue, more  a task list for me.
we can discuss things here if required. ideas suggestion, ...

**Comment by a4z** [comment]
all points are handled in todays pull request for the cmake re factoring branch
so I think we should close this now?

there are still a lot of todos, but they might be handled and assigned via extra with issues, 
(looking on the other issues, I think removing, or changing, the build.sh could have highest priority)

**Comment by grantila** [comment]
I'll test this out for Mac and Windows as well possibly tomorrow or at least in the weekend and close this (and merge to master). Thanks for the work thus far!

**Comment by grantila** [comment]
Closed by a8ff87dcdb5165201417188b3ad7e930c5f1962e
