### ISSUE TITLE
64-bit visual studio build does not work

### ISSUE THREAD

**Issue by rogierschouten** [grantila/q#5]
Problem:
- use VS2015
- run build.sh and open the solution
- add x64 configuration using configuration manager
- build the q project x64, results in linker error LNK1112

Solution:
- go to project properties -> Librarian -> All Options
- clear the setting for "Additional Options"

Issue:
- maybe add 64-bit configuration by default when running build.sh

**Comment by rogierschouten** [comment]
By the way, thank you for creating this - it's a relief to be able to use real promises in C++

**Comment by grantila** [comment]
Thanks!

I'll have a look at the default arguments being used, to see if this can be elegantly fixed for all targets.

**Comment by grantila** [comment]
CMake cannot output a solution file for multiple architectures, according to http://stackoverflow.com/a/28370892/1498550
Will push an updated README for up-to-date CMake build instructions.
